In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

df = pd.read_excel('AU_Car_Recalls.xlsx')
df.head()

        Date  Car_ID System_Affected    Units      Model
0 2024-12-27  147160           Tires  12623.0  Champlain
1 2024-12-25   99110           Tires   1337.0     Salish
2 2024-12-24   87110      Powertrain   1905.0   Beaufort
3 2024-12-22   26151          Engine   4019.0     Hudson
4 2024-12-08  147160      Suspension  12978.0  Champlain

In [ ]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 163 entries, 0 to 162
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             163 non-null    datetime64[ns]
 1   Car_ID           163 non-null    int64
 2   System_Affected  163 non-null    object
 3   Units            163 non-null    float64
 4   Model            163 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(1), object(2)
memory usage: 6.5+ KB

Date               0
Car_ID             0
System_Affected    0
Units              0
Model              0
dtype: int64

In [ ]:
# Hapus data penting yang kosong
df = df.dropna(subset=['Date', 'Car_ID', 'System_Affected'])

# Rapikan text
df['System_Affected'] = df['System_Affected'].str.upper().str.strip()
df['Model'] = df['Model'].str.upper().str.strip()

# Isi unit kosong
df['Units'] = df['Units'].fillna(0)

# Convert tanggal
df['Date'] = pd.to_datetime(df['Date'])

In [ ]:
df['year'] = df['Date'].dt.year
df['month'] = df['Date'].dt.month

In [ ]:
summary = df.groupby(['Model', 'System_Affected']).agg(
    total_unit=('Units', 'sum'),
    total_case=('Car_ID', 'count')
).reset_index()

summary

        Model         System_Affected    total_unit  total_case
0    BEAUFORT                  AIRBAG  70422.353898           9
1    BEAUFORT                  BRAKES  19875.942072           2
2    BEAUFORT              ELECTRICAL  13874.000000           1
3    BEAUFORT                  ENGINE  30884.000000           3
4    BEAUFORT             FUEL SUPPLY  23186.000000           2
5    BEAUFORT  LIGHTS AND INSTRUMENTS  23892.184900           2
6    BEAUFORT                   OTHER  24394.670576           2
7    BEAUFORT              POWERTRAIN  30583.000000           3
8    BEAUFORT    SEATS AND RESTRAINTS   3396.000000           1
9    BEAUFORT              SUSPENSION  44285.878535           4
10   BEAUFORT           VISUAL SYSTEM  18407.000000           3
11  CHAMPLAIN                  AIRBAG   9866.000000           1
12  CHAMPLAIN                  ENGINE   9293.000000           3
13  CHAMPLAIN             FUEL SUPPLY   4048.000000           1
14  CHAMPLAIN                   OTHER  14346.000000           1
15  CHAMPLAIN              POWERTRAIN  42770.000000           6
16  CHAMPLAIN    SEATS AND RESTRAINTS  47022.183947           6
17  CHAMPLAIN                STEERING  24964.000000           2
18  CHAMPLAIN              SUSPENSION  60940.733805           5
19  CHAMPLAIN                   TIRES  20863.000000           2
20  CHAMPLAIN           VISUAL SYSTEM  25595.762603           6
21     HUDSON                  AIRBAG  52041.631636           8
22     HUDSON              ELECTRICAL   5864.000000           2
23     HUDSON                  ENGINE  26755.469152           3
24     HUDSON             FUEL SUPPLY   8577.000000           2
25     HUDSON                   OTHER  34708.018792           3
26     HUDSON              POWERTRAIN  14974.498725           4
27     HUDSON    SEATS AND RESTRAINTS  41762.000000           4
28     HUDSON                STEERING   3666.261129           2
29     HUDSON              SUSPENSION   8952.000000           2
30     HUDSON                   TIRES  11213.000000           1
31     HUDSON           VISUAL SYSTEM  17118.000000           2
32   LABRADOR                  AIRBAG  32595.184021           6
33   LABRADOR              ELECTRICAL  14556.000000           3
34   LABRADOR                  ENGINE  30106.961373           3
35   LABRADOR             FUEL SUPPLY  18356.156970           2
36   LABRADOR  LIGHTS AND INSTRUMENTS   5610.028936           2
37   LABRADOR    SEATS AND RESTRAINTS  26380.000000           2
38   LABRADOR                STEERING  18824.000000           3
39   LABRADOR               STRUCTURE  24957.145225           2
40   LABRADOR              SUSPENSION  30247.000000           3
41   LABRADOR                   TIRES  40047.000000           4
42   LABRADOR           VISUAL SYSTEM  31093.000000           3
43     SALISH                  AIRBAG  29038.633292           6
44     SALISH                  ENGINE   3300.000000           1
45     SALISH  LIGHTS AND INSTRUMENTS  27446.000000           2
46     SALISH                   OTHER   3583.814076           2
47     SALISH              POWERTRAIN  32864.000000           4
48     SALISH    SEATS AND RESTRAINTS  28416.000000           2
49     SALISH                STEERING  19066.000000           2
50     SALISH               STRUCTURE  37295.576579           6
51     SALISH                   TIRES  29223.695948           7

In [ ]:
df.to_csv('clean_data.csv', index=False)
summary.to_csv('summary.csv', index=False)

from google.colab import files
files.download('clean_data.csv')
files.download('summary.csv')